{% set version = "0.3.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-beeswarm
  version: {{ version|replace("-", "_") }}

source:
  fn: beeswarm_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/beeswarm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/beeswarm/beeswarm_{{ version }}.tar.gz
  sha256: 525e61e71206feab28885d90a0311a09a2ebc66a730016d984e770eeaf7f4fcb

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('beeswarm')"           # [not win]
    - "\"%R%\" -e \"library('beeswarm')\""  # [win]

about:
  home: http://www.cbs.dtu.dk/~eklund/beeswarm/
  license: Artistic-2.0
  summary: 'The bee swarm plot is a one-dimensional scatter plot like "stripchart", but with closely-packed, non-overlapping points. '

  license_family: OTHER

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0
extra:
  recipe-maintainers:
    - conda-forge/r
    - jdblischak
    - johanneskoester
    - bgruening
    - nsoranzo
