{% set version = "0.4.0" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-beeswarm
  version: {{ version|replace("-", "_") }}

source:
  fn: beeswarm_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/beeswarm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/beeswarm/beeswarm_{{ version }}.tar.gz
  sha256: 51f4339bf4080a2be84bb49a844c636625657fbed994abeaa42aead916c3d504

build:
  number: 4
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('beeswarm')"           # [not win]
    - "\"%R%\" -e \"library('beeswarm')\""  # [win]

about:
  home: http://www.cbs.dtu.dk/~eklund/beeswarm/
  license: Artistic-2.0
  summary: 'The bee swarm plot is a one-dimensional scatter plot like "stripchart", but with closely-packed, non-overlapping points. '
  license_family: OTHER
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0

extra:
  recipe-maintainers:
    - conda-forge/r
    - nsoranzo
