travis:
  secure:
    BINSTAR_TOKEN: WVNsgh062OyMJM85V3QyfgxEgccu4pRCwXd8WSgxoZeKajeFlLfRkckzjGVc30tN9US4cTd07OLAPydh5iZYjSQFL/YiNX68fShE7ps90pZLX8wOXxcF6muKr7iogVieGpWLQJJQ62hiCjnaff6X4ynKBQ0LQsrATRM7lImoUecy1gOypRtSZj/9KMEdrFNWDKfOwfkS3T6ctismeyM75w1UEmeU/Mz0aLYVmIOY8Nqn+lNJlsdUR5IRQajAz2q5sKuu0QgaEFTuKv7EZ8VpthrgZF7WmFO8OqOVVNnXdZ7BNZ6WfEJZ/p6/CRit2zyNCwghiXrkht1gN8KrCP3/gy9nIe/megIHOslRm53YOZ5K4Gl31IXIz6wTMaA1Ea70LySOtGWIbiU8+NpbQpQyIIuIYftA4szKju3ErFiM73lJO4i2ssOkmGptbibrUs7GD5W0fZp0TDYJ9vUc4v31NTU1ewXMWnB0+PhY4Tdd6coj5JLPIen5WDyocJ8ZjvsJR+UYhLbow0AfIB/TOvxhBVWHfVBX3CRJ0Al1csitg5Gzbk0ggRK0CAaHOTBA9PUkytOXhw+Y6WOC4jC03lRxuMzkvBhDop4I+5MABa2OxfmthF+vTJV0Z91MGBz/vQRAhUOHUn6n1mP/Fd+tRlYCWrfeSvhdJMmCwocD/JnLrio=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
