travis:
  secure:
    BINSTAR_TOKEN: Z9MbAtL7wRVHTXfFYTzjuSe9ENSdneNhnucuHtz40R3+iyLA/xmB2ya+ptPewjwP3o+2o313mBU2EfW4tY8XIjXm1+xltnAXSfDU4dwawXj9VcCIPMzuCKvKXHa6TTeH5tbY14HGtfRnpoEKtR/MsfwXNFA0Zj5oNO+OQcvFYQpH5lOMrd7gx3OCUSNL8ycMsIMCcq1xctjrUhBGGVBRW+bVrrLyqK0OzXWVFI9tuLGHQkrGwd9aKdUdI+Z+qc0d0NUnH51yCgYeHCGldCh4EbDAFu00bPjJeo/4unnLwciAeg62rTT7oEi8DMgA4ctMneaaKjCgJuFy4Ca7yZRCLck+2nR8DGf6xHsSEp6hdfYCMSTe6OzY6Lg/r76aI5XRSis3jyrmRByFVduWVBc6hD3bg3LQT0HeyvdBMiMPFjMJxSM5Gg4dguxhq8F4BvBJbyKMyu65y+lX9XiFpYWTkO+2m7xHzuRbfkrU0NNuXla/PLhaY7oXyVyByPSRVrTy130FKxqpdHOQJ/LNgtadUw+rpZib3vnNV8zmZMCyZLeC0hCUKTxlmx230pw0ztuS6zGuhE5PbFN6jPJ4KDWjhF0N3ofy3UywjrdDqhfE6krC1adp05XLrVanbZiMq+iBIXvM/UYeaK2pokOOJ27paKbeD3bPakBPNCKt307+FiM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
